In [40]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

df_raw = pd.read_csv('../podatki/bicikelj_train.csv')
df_raw['timestamp'] = pd.to_datetime(df_raw['timestamp'])

df_padavine = pd.read_csv('../podatki/padavine.csv')



df_padavine = df_padavine.drop('station id', axis=1)
df_padavine = df_padavine.drop(' station name', axis=1)

df_padavine.rename(columns={' valid': 'timestamp'}, inplace=True)
df_padavine.rename(columns={'količina padavin [mm]': 'prcp'}, inplace=True)
df_padavine.rename(columns={'povp. T [°C]': 'avgT'}, inplace=True)

categories = ['Very Low', 'Low', 'Moderate', 'High', 'Very High']

# Categorize the temperature column
df_padavine['Temperature Category'] = pd.cut(df_padavine['avgT'], bins=5, labels=categories)

# Perform one-hot encoding
one_hot_encoded = pd.get_dummies(df_padavine['Temperature Category'], prefix='Temperature').astype(int)

# Concatenate the one-hot encoded DataFrame with the original DataFrame
df_encoded = pd.concat([df_padavine, one_hot_encoded], axis=1)

# Remove the original temperature column and the temperature category column if needed
df_encoded.drop(['avgT', 'Temperature Category'], axis=1, inplace=True)

df_padavine['timestamp'] = pd.to_datetime(df_padavine['timestamp'])
df_padavine['timestamp'] = pd.to_datetime(df_padavine['timestamp'])

df_padavine = df_padavine.dropna()

merged_df = pd.merge_asof(df_raw, df_padavine, on='timestamp', direction='nearest')

# Define the temperature categories
    

display(df_encoded.head(10))

,timestamp,prcp,Temperature_Very Low,Temperature_Low,Temperature_Moderate,Temperature_High,Temperature_Very High
0,2022-08-01 00:00,0.0,0,0,1,0,0
1,2022-08-01 00:10,NaN,0,0,1,0,0
2,2022-08-01 00:20,NaN,0,0,1,0,0
3,2022-08-01 00:30,0.0,0,0,1,0,0
4,2022-08-01 00:40,NaN,0,0,1,0,0
5,2022-08-01 00:50,NaN,0,0,1,0,0
6,2022-08-01 01:00,0.0,0,0,1,0,0
7,2022-08-01 01:10,NaN,0,0,1,0,0
8,2022-08-01 01:20,NaN,0,0,1,0,0
9,2022-08-01 01:30,0.0,0,0,1,0,0